//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestCase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _16Kints {
            get {
                return ResourceManager.GetString("_16Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1Kints {
            get {
                return ResourceManager.GetString("_1Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1Mints {
            get {
                return ResourceManager.GetString("_1Mints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _2Kints {
            get {
                return ResourceManager.GetString("_2Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _32Kints {
            get {
                return ResourceManager.GetString("_32Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _4Kints {
            get {
                return ResourceManager.GetString("_4Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _8Kints {
            get {
                return ResourceManager.GetString("_8Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000
        ///786321 134521
        ///696834 98245
        ///135991 549478
        ///44723 265931
        ///698410 385074
        ///605706 520899
        ///462258 656850
        ///807101 778785
        ///400066 73310
        ///51236 774849
        ///73567 396244
        ///131311 706500
        ///460661 848448
        ///516872 565515
        ///527941 319687
        ///798741 997522
        ///271929 192591
        ///911577 210982
        ///791065 737806
        ///687418 74244
        ///392085 820718
        ///652701 787472
        ///753794 949786
        ///163885 920239
        ///410914 167848
        ///420667 443969
        ///289052 39203
        ///364160 479678
        ///673290 368819
        ///553341 507436
        ///686513 37739
        ///759235 691066
        ///923788 334896
        ///442703 249149
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string largeUF {
            get {
                return ResourceManager.GetString("largeUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 625
        ///528 503
        ///548 523
        ///389 414
        ///446 421
        ///552 553
        ///154 155
        ///173 174
        ///373 348
        ///567 542
        ///44 43
        ///370 345
        ///546 547
        ///204 229
        ///404 429
        ///240 215
        ///364 389
        ///612 611
        ///513 512
        ///377 376
        ///468 443
        ///410 435
        ///243 218
        ///347 322
        ///580 581
        ///188 163
        ///61 36
        ///545 546
        ///93 68
        ///84 83
        ///94 69
        ///7 8
        ///619 618
        ///314 339
        ///155 156
        ///150 175
        ///605 580
        ///118 93
        ///385 360
        ///459 458
        ///167 168
        ///107 108
        ///44 69
        ///335 334
        ///251 276
        ///196 197
        ///501 502
        ///212 187
        ///251 250
        ///269 270
        ///332 331
        ///125 150
        ///391 416
        ///366 367
        ///65 40
        ///515 540
        ///248 273
        ///34 9
        ///480 479
        ///198 173 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mediumUF {
            get {
                return ResourceManager.GetString("mediumUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///4 3
        ///3 8
        ///6 5
        ///9 4
        ///2 1
        ///8 9
        ///5 0
        ///7 2
        ///6 1
        ///1 0
        ///6 7
        ///.
        /// </summary>
        public static string tinyUF {
            get {
                return ResourceManager.GetString("tinyUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///0 1
        ///0 2
        ///0 3
        ///0 4
        ///0 5
        ///0 6
        ///0 7
        ///0 8
        ///0 9
        ///.
        /// </summary>
        public static string worstUF {
            get {
                return ResourceManager.GetString("worstUF", resourceCulture);
            }
        }
    }
}
