//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortUnionTest.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SortUnionTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _32Kints {
            get {
                return ResourceManager.GetString("_32Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -999985
        ///-999964
        ///-999905
        ///-999894
        ///-999639
        ///-999591
        ///-999590
        ///-999344
        ///-999218
        ///-999100
        ///-999021
        ///-999018
        ///-998862
        ///-998811
        ///-998793
        ///-998595
        ///-998586
        ///-998568
        ///-998477
        ///-998394
        ///-998375
        ///-998343
        ///-998337
        ///-998274
        ///-998200
        ///-998166
        ///-998111
        ///-997981
        ///-997925
        ///-997900
        ///-997864
        ///-997854
        ///-997719
        ///-997713
        ///-997684
        ///-997670
        ///-997661
        ///-997628
        ///-997549
        ///-997547
        ///-997539
        ///-997332
        ///-997329
        ///-997316
        ///-997310
        ///-997294
        ///-997258
        ///-997157
        ///-996957
        ///-996916
        ///-996906
        ///-996854
        ///-996693
        ///-996664
        ///-996609
        ///-996424
        ///-996409        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string _32Kints_Sorted {
            get {
                return ResourceManager.GetString("_32Kints_Sorted", resourceCulture);
            }
        }
    }
}
